# Generated by Django 4.2.5 on 2023-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0002_alter_customer_balance_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('total_shipped', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('customer_id', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('unit', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_ord', models.DecimalField(decimal_places=2, max_digits=15)),
                ('supplier', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('purchese_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('passowrd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
