# Generated by Django 4.2.6 on 2023-10-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0003_brand_category_order_product_purchase_supplier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
