# Generated by Django 4.2.6 on 2023-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0005_alter_product_min_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
