# Generated by Django 4.2.6 on 2023-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0006_alter_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchese_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
