# Generated by Django 4.2.6 on 2023-10-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0007_alter_purchase_purchese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='bname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invapk.category'),
        ),
    ]
