# Generated by Django 4.2.6 on 2023-10-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0008_alter_brand_bname'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invapk.category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='bname',
            field=models.CharField(max_length=100),
        ),
    ]
