# Generated by Django 4.2.6 on 2023-10-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0009_brand_name_alter_brand_bname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='bname',
            new_name='Bname',
        ),
    ]
