# Generated by Django 4.2.6 on 2023-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0012_rename_bname_brand_b_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
