# Generated by Django 4.2.6 on 2023-10-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0014_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invapk.brand'),
        ),
    ]
