# Generated by Django 4.2.6 on 2023-10-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0016_alter_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplier_name',
        ),
    ]
