# Generated by Django 4.2.6 on 2023-10-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0019_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invapk.supplier'),
        ),
    ]
