# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0021_alter_supplier_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invapk.supplier'),
        ),
    ]
