# Generated by Django 4.2.6 on 2023-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapk', '0023_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
